app = "swsa-courses"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8081"

[[services]]
  internal_port = 8081
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [services.http_checks]
    path = "/health"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
